# Generated by Django 5.2.1 on 2026-05-28 05:09

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UploadBatch',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=32)),
                ('file_name', models.CharField(max_length=512)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='upload_batches', to='tenants.organization')),
            ],
        ),
        migrations.CreateModel(
            name='IngestionJob',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('uploaded_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('file_name', models.CharField(max_length=512)),
                ('checksum', models.CharField(blank=True, max_length=128)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=32)),
                ('records_total', models.IntegerField(default=0)),
                ('records_failed', models.IntegerField(default=0)),
                ('error_log', models.JSONField(blank=True, default=dict)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ingestion_jobs', to='tenants.organization')),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='jobs', to='ingestion.uploadbatch')),
            ],
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['organization', 'created_at'], name='ingestion_u_organiz_df3042_idx'),
        ),
        migrations.AddIndex(
            model_name='uploadbatch',
            index=models.Index(fields=['source_type', 'created_at'], name='ingestion_u_source__4a071f_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['organization', 'uploaded_at'], name='ingestion_i_organiz_58729b_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['source_type', 'uploaded_at'], name='ingestion_i_source__0d8d8f_idx'),
        ),
        migrations.AddIndex(
            model_name='ingestionjob',
            index=models.Index(fields=['upload_batch', 'uploaded_at'], name='ingestion_i_upload__19fbe8_idx'),
        ),
    ]
