# Generated by Django 5.2.1 on 2026-05-28 05:09

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ingestion', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmissionRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('amount', models.DecimalField(decimal_places=6, default=Decimal('0'), max_digits=20)),
                ('unit', models.CharField(default='kgCO2e', max_length=50)),
                ('period', models.CharField(max_length=64)),
                ('scope', models.CharField(choices=[('scope_1', 'Scope 1'), ('scope_2', 'Scope 2'), ('scope_3', 'Scope 3')], max_length=16)),
                ('source_type', models.CharField(choices=[('sap', 'SAP'), ('utility', 'Utility'), ('travel', 'Travel')], max_length=32)),
                ('source_ref', models.JSONField(blank=True, default=dict)),
                ('raw_payload', models.JSONField(blank=True, default=dict)),
                ('normalized_payload', models.JSONField(blank=True, default=dict)),
                ('flag_reasons', models.JSONField(blank=True, default=list)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('pending_review', 'Pending Review'), ('approved', 'Approved'), ('failed', 'Failed'), ('rejected', 'Rejected')], default='pending', max_length=32)),
                ('normalization_version', models.CharField(default='v1', max_length=32)),
                ('normalized_at', models.DateTimeField(blank=True, null=True)),
                ('normalization_notes', models.TextField(blank=True, default='')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True, null=True)),
                ('ingestion_job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='ingestion.ingestionjob')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='emission_records', to='tenants.organization')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('upload_batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='emission_records', to='ingestion.uploadbatch')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'status'], name='emissions_e_organiz_a7c7c2_idx'), models.Index(fields=['organization', 'source_type'], name='emissions_e_organiz_db4a2d_idx'), models.Index(fields=['organization', 'scope'], name='emissions_e_organiz_cfc59b_idx'), models.Index(fields=['ingestion_job', 'status'], name='emissions_e_ingesti_32bb5c_idx'), models.Index(fields=['upload_batch', 'created_at'], name='emissions_e_upload__eaba95_idx'), models.Index(fields=['created_at'], name='emissions_e_created_bcd8b4_idx')],
            },
        ),
        migrations.CreateModel(
            name='UnitConversion',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('from_unit', models.CharField(max_length=50)),
                ('to_unit', models.CharField(max_length=50)),
                ('factor', models.DecimalField(decimal_places=12, max_digits=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='unit_conversions', to='tenants.organization')),
            ],
            options={
                'indexes': [models.Index(fields=['organization', 'from_unit', 'to_unit'], name='emissions_u_organiz_a72583_idx')],
            },
        ),
    ]
